#!/bin/bash
wget https://archive.org/download/StarWarsIVANewHope1977/Star%20Wars%20IV%20-%20A%20New%20Hope%20%281977%29.mp4 -O starwars.mp4
if ! [ -x "$(command -v mpv)" ]; then
  sudo apt-get update
  sudo apt-get install mpv
fi
mpv starwars.mp4
